import Header from "@/components/MainComponents/Header";
import { StoreProvider } from "@/store/StoreProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <main className="min-h-screen flex flex-col items-center lg:py-24 max-w-screen-xl mx-auto">
            {children}
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
